# Generated by Django 5.0.4 on 2024-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class to create the initial Task model.

    Attributes:
        initial (bool): Indicates if this is the initial migration.
        dependencies (list): A list of migration dependencies.
        operations (list): A list of operations to be performed in this migration.
    """
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("priority", models.IntegerField()),
            ],
        ),
    ]
