# Generated by Django 5.0.4 on 2024-04-25 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migrtion class to add a date field to the Task model.

    Attributes:
        dependencies (list): A list of migration dependencies.
        operations (list): A list of operations to be performed in this migration.
    """
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
